@echo off
echo Stopping Service on port 8081...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8081" ^| find "LISTENING"') do taskkill /f /pid %%a
echo Service stopped.
echo Starting backend...
call start-backend.bat
