@echo off
echo [LOG] Killing existing java processes...
taskkill /F /IM java.exe
echo [LOG] Building backend...
call mvn clean package -DskipTests
echo [LOG] Starting backend...
start /B java -jar target\coffee-shop-backend-1.0.0.jar > app_output.log 2>&1
echo [LOG] Backend started. Check app_output.log for details.
